version: "3.8"

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=flaskmysql
      - MYSQL_ROOT_PASSWORD=example

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - flask
